### ISSUE TITLE
Portal proxy sends Host header twice

### ISSUE THREAD

**Issue by mie00** [Jumpscale/portal9#43]
#### Installation information

- jumpscale version: 9.0.3
- operating system: Ubuntu Xenial

#### Detailed description

Portal proxy sends Host header twice which causes grafana to respond with bad request.

#### Steps to reproduce

1. run a netcat server to listen to tcp connections

`nc -l 127.0.0.1 1239`

2. add a proxy in portal to this address

```yaml
cfg.proxy:
  aysapi:
    path: /api/ays
    dest: 'http://127.0.0.1:1239'
```

3. Check the output of netcat

#### Relevant stacktraces

That is what I get in netcat output

```
GET / HTTP/1.1
Host: 127.0.0.1:1239
...
HOST: myhost.com
```
